### PR TITLE
Fix license attribution

### PR DESCRIPTION
**Pull request by 3nprob**
Mistakenly removed in 04c7143a39a0bb243369e31f3b3b797449468fdb

### CODE REVIEW

**Review by kblok — APPROVED** [review]

**Comment by ryanbnl** [comment]
Merge or no cigar :-)

**Comment by serprex** [comment]
All 5 commits should be reverted

Someone on reddit pointed out this issue impacts multiple forks: https://www.reddit.com/r/opensource/comments/roa9xz/comment/hpx67x2/?utm_source=share&utm_medium=web2x&context=3

The bot should ignore forks

**Comment by 3nprob** [comment]
> 

Altfront links:

https://libredd.it/r/opensource/comments/roa9xz/comment/hpx67x2

https://kphht2jcflojtqte4b4kyx7p2ahagv4debjj32nre67dxz7y57seqwyd.onion/r/opensource/comments/roa9xz/comment/hpx67x2

https://reddit.lol/r/opensource/comments/roa9xz/comment/hpx67x2

https://ibarajztopxnuhabfu7fg6gbudynxofbnmvis3ltj6lfx47b6fhrd5qd.onion/r/opensource/comments/roa9xz/comment/hpx67x2

**Comment by 3nprob** [comment]
> All 5 commits should be reverted

Maybe make a complimentary PR for that? :) Perhaps split out 04c7143 to facilitate smooth merging of the two.

**Review by veselcraft — COMMENTED** [review]
that dot

**Comment by mfcallahan** [comment]
For shame. Caught red handed.

**Pull request merged**
